# Run MySQL instead of Cassandra
storage:
  image: openzipkin/zipkin-mysql:1.37.0
  ports:
    - 3306:3306

# Switch storage type to MySQL
query:
  environment:
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
