# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It runs the zipkin and zipkin-cassandra containers, using docker-compose's
# default networking to wire the containers together.

version: '2'

services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is enabled by default.
  zipkin:
    image: openzipkin/zipkin:1.8.2
    container_name: zipkin
    ports:
      # Listen port for the Scribe transport
      - 9410:9410
      # Historical port used for the Zipkin HTTP Api
      - 9411:9411
      # Zipkin UI used to be on a separate process listening on port 8080
      - 8080:9411
