mysql:
  image: openzipkin/zipkin-mysql:1.17.1
  ports:
    - 3306:3306
collector:
  image: openzipkin/zipkin-collector:1.17.1
  environment:
    - STORAGE_TYPE=mysql
  expose:
    - 9410
  ports:
    - 9410:9410
    - 9900:9900
  links:
    - mysql:storage
query:
  image: openzipkin/zipkin-query:1.17.1
  environment:
    - STORAGE_TYPE=mysql
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - mysql:storage
    - collector
web:
  image: openzipkin/zipkin-web:1.17.1
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - collector
    - query
