# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to run the
# zipkin-mysql container instead of the zipkin-cassandra container.

version: '2'

services:
  # Run MySQL instead of Cassandra
  storage:
    image: openzipkin/zipkin-mysql:1.8.4
    container_name: mysql
    ports:
      - 3306:3306

  # Switch storage type to MySQL
  zipkin:
    image: openzipkin/zipkin:1.8.4
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
  dependencies:
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
