mysql:
  image: openzipkin/zipkin-mysql:1.23.1
  ports:
    - 3306:3306
query:
  image: openzipkin/zipkin-query:1.23.1
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
  links:
    - mysql:storage
web:
  image: openzipkin/zipkin-web:1.23.1
  environment:
    # Remove TRANSPORT_TYPE to disable tracing
    - TRANSPORT_TYPE=http
  ports:
    - 8080:8080
    - 9990:9990
  links:
    - query
